kind: ReplicationController
id: phone-controller
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    name: phone
    version: v1
  podTemplate:
    labels:
      name : phone
      version: v1
    desiredState:
      manifest:
        containers:
          - name: phone
            image: clemble/phone:latest
            imagePullPolicy : PullAlways
            ports:
              - containerPort: 10003
                hostPort: 10003
                protocol: TCP
            labels:
              name : phone
              version: v1
